<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="publictransport" nsURI="http://jena.de/udp/trafficos/publictransport/1.0"
    nsPrefix="publictransport">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportConfiguration" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicTransport" upperBound="-1"
        eType="#//PublicTransportLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportLine" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeTable" upperBound="-1"
        eType="#//PublicTransportTimeTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTimeTable" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//PublicTransportTimeTableEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//ScheduleModeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTimeTableEntry" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//AbstractTimeTableEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstStation" lowerBound="1"
        eType="#//PublicTransportStation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastStation" lowerBound="1"
        eType="#//PublicTransportStation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stops" upperBound="-1"
        eType="#//PublicTransportStop" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportStop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="station" eType="#//PublicTransportStation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedArrivalTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minute of the day"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportStation" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EClass ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorSide" eType="#//PublicTransportDoorSideType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDataEntry" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//AbstractDataEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataValue" upperBound="-1"
        eType="#//PublicTransportDataValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportDataValueType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineRef" eType="ecore:EClass ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PublicTransportDataValueObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeTableEntryRef" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This should reference to the index of the TimeTableEntry this value is referring to. This because a line can have multiple physical vehicles running around, so we should refer to the timetable. E.g. Tram line 2 has schedule departures at 7:03, 7:13, 7:23, ect so we should be able to identify to which trip the data is referring to."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDataValueObject" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTelegram" eSuperTypes="#//PublicTransportDataValueObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportPosition" eSuperTypes="#//PublicTransportDataValueObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EClass ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="atStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDoorChange" eSuperTypes="#//PublicTransportPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorSide" eType="#//PublicTransportDoorSideType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportDoorChangeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportLocMsg" eSuperTypes="#//PublicTransportDataValueObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tripNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kilometer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="odo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="door" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDoorCount" eSuperTypes="#//PublicTransportDataValueObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorSide" eType="#//PublicTransportDoorSideType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportDoorCountingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="out" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportStopRequested" eSuperTypes="#//PublicTransportDataValueObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopRequested" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportType">
    <eLiterals name="TRAM"/>
    <eLiterals name="CITY_BUS" value="1"/>
    <eLiterals name="REGIONAL_BUS" value="2"/>
    <eLiterals name="OTHER" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDataValueType">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="DOOR_CHANGE" value="1"/>
    <eLiterals name="TELEGRAM" value="2"/>
    <eLiterals name="GEO_INFO" value="3"/>
    <eLiterals name="LOCATION_MESSAGE" value="4"/>
    <eLiterals name="DOOR_COUNT" value="5"/>
    <eLiterals name="STOP_REQUESTED" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDoorChangeType">
    <eLiterals name="DOOR_CLOSE"/>
    <eLiterals name="DOOR_OPEN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDoorCountingType">
    <eLiterals name="ADULT"/>
    <eLiterals name="CHILD" value="1"/>
    <eLiterals name="BIKE" value="2"/>
    <eLiterals name="WHEEL_CHAIR" value="3"/>
    <eLiterals name="PARAM" value="4"/>
    <eLiterals name="UNIDENTIFIED" value="5"/>
    <eLiterals name="OTHER" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDoorSideType">
    <eLiterals name="RIGHT"/>
    <eLiterals name="LEFT" value="1"/>
  </eClassifiers>
</ecore:EPackage>
