<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="publictransport" nsURI="http://jena.de/udp/trafficos/publictransport/1.0"
    nsPrefix="publictransport">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportConfiguration" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdNameElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publicTransport" upperBound="-1"
        eType="#//PublicTransport" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransport" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeTable" upperBound="-1"
        eType="#//PublicTransportTimeTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTimeTable" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" upperBound="-1"
        eType="#//PublicTransportTimeTableEntry" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//ScheduleModeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTimeTableEntry" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//AbstractTimeTableEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicTransportId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstStop" lowerBound="1"
        eType="#//PublicTransportStop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastStop" lowerBound="1"
        eType="#//PublicTransportStop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stops" upperBound="-1"
        eType="#//PublicTransportStop" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This would contain the intermediate stops, excluding the first and last."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportStop" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The id of this object should be something like the DHID-Code, EPON-Code, etc."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EClass ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedArrivalTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minute of the day"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduledArrivalTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minute of the day"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedDepartureTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minute of the day"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduledDepartureTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Minute of the day"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlyOnRequest" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether the stop is a planned one or is only on demand"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDataEntry" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//AbstractDataEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicTransportId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportDataValueType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PublicTransportDataValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The source of this data update (Ibis, VDV, etc.). Might be useful for further filtering in the API."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDataValue" eSuperTypes="../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//IdElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTelegram" eSuperTypes="#//PublicTransportDataValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportPosition" eSuperTypes="#//PublicTransportDataValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="ecore:EClass ../../de.jena.udp.trafficos.common.model/model/tos-common.ecore#//Position"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDoorChange" eSuperTypes="#//PublicTransportPosition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorSide" eType="#//PublicTransportDoorSideType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportDoorChangeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportLocMsg" eSuperTypes="#//PublicTransportDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tripNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kilometer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextStop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="odo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="door" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportDoorCount" eSuperTypes="#//PublicTransportDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorSide" eType="#//PublicTransportDoorSideType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PublicTransportDoorCountingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="in" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="out" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportStopRequested" eSuperTypes="#//PublicTransportDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopRequested" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTripData" eSuperTypes="#//PublicTransportDataValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tripRef" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stops" upperBound="-1"
        eType="#//PublicTransportStop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timetableDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delay in seconds. Early times are shown as negative values."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationState" eType="#//PublicTransportLocationStateType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublicTransportTimetable" eSuperTypes="#//PublicTransportDataValue">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This update value should contain changes to a nominal timetable entry."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entry" eType="#//PublicTransportTimeTableEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportType">
    <eLiterals name="TRAM"/>
    <eLiterals name="CITY_BUS" value="1"/>
    <eLiterals name="REGIONAL_BUS" value="2"/>
    <eLiterals name="E_BUS" value="3"/>
    <eLiterals name="OTHER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDataValueType">
    <eLiterals name="UNKNOWN"/>
    <eLiterals name="DOOR_CHANGE" value="1"/>
    <eLiterals name="TELEGRAM" value="2"/>
    <eLiterals name="GEO_INFO" value="3"/>
    <eLiterals name="LOCATION_MESSAGE" value="4"/>
    <eLiterals name="DOOR_COUNT" value="5"/>
    <eLiterals name="STOP_REQUESTED" value="6"/>
    <eLiterals name="TRIP_DATA" value="7"/>
    <eLiterals name="TIMETABLE" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDoorChangeType">
    <eLiterals name="DOOR_CLOSE"/>
    <eLiterals name="DOOR_OPEN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDoorCountingType">
    <eLiterals name="ADULT"/>
    <eLiterals name="CHILD" value="1"/>
    <eLiterals name="BIKE" value="2"/>
    <eLiterals name="WHEEL_CHAIR" value="3"/>
    <eLiterals name="PARAM" value="4"/>
    <eLiterals name="UNIDENTIFIED" value="5"/>
    <eLiterals name="OTHER" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportDoorSideType">
    <eLiterals name="RIGHT"/>
    <eLiterals name="LEFT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicTransportLocationStateType">
    <eLiterals name="AFTER_STOP"/>
    <eLiterals name="AT_STOP" value="1"/>
    <eLiterals name="BEFORE_STOP" value="2"/>
    <eLiterals name="BETWEEN_STOP" value="3"/>
  </eClassifiers>
</ecore:EPackage>
